### ISSUE TITLE
Model ID not exported? No way to link the exported data to the original model?

### ISSUE THREAD

**Issue by emawind84** [pipauwel/IFC.JAVA#5]
Hi,
In the ifc file there is an id for every object but in the xml or json generated I don't see this id, instead I see a new generated guid. We need to link some extra data to the actual model but without the original identifier I don't know how I can link the parsed data to the original object in the ifc model.

I am talking about the first number at the start of the line.
```
...
#1= IFCORGANIZATION($,'Autodesk Revit 2019 (ENU)',$,$,$);
#5= IFCAPPLICATION(#1,'2019','Autodesk Revit 2019 (ENU)','Revit');
#6= IFCCARTESIANPOINT((0.,0.,0.));
#9= IFCCARTESIANPOINT((0.,0.));
#11= IFCDIRECTION((1.,0.,0.));
#13= IFCDIRECTION((-1.,0.,0.));
...
```

**Comment by pipauwel** [comment]
Thanks for posting this issue. The project is however not actively maintained any more and also closed now. My apologies and hopefully you will find better resources.
